name: Sample-Jupyter-notebooks
channels:
  - conda-forge

dependencies:
  # Core scientific python
  - numpy
  - matplotlib
  - python>=3.6
  - seaborn

  # Natural language processing
  - tweepy
  - nltk
  - textblob

  - pip:
      # Utilities
      - download
      - nbclean
